[build]
builder = "RAILPACK"
buildCommand = "pnpm install --frozen-lockfile && pnpm exec turbo run build --filter=@exness/batch-uploader"
watchPatterns = ["apps/batch-uploader/**", "packages/**", "pnpm-lock.yaml", "package.json"]

[deploy]
startCommand = "pnpm --filter @exness/batch-uploader start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
