export const ERROR_CODES = [
  'INVALID_INPUT',
  'AUTH_REQUIRED',
  'FORBIDDEN',
  'BAD_CREDENTIALS',
  'BREACHED_PASSWORD',
  'USER_EXISTS',
  'ASSET_NOT_FOUND',
  'INSUFFICIENT_BALANCE',
  'INVALID_LEVERAGE',
  'ORDER_NOT_FOUND',
  'ORDER_ALREADY_CLOSED',
  'PRICE_UNAVAILABLE',
  'IN_FLIGHT',
  'INTERNAL_ERROR',
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];
