[build]
builder = "RAILPACK"
buildCommand = "pnpm install --frozen-lockfile && pnpm exec turbo run build --filter=@exness/ws-server"
watchPatterns = ["apps/ws-server/**", "packages/**", "pnpm-lock.yaml", "package.json"]

[deploy]
startCommand = "pnpm --filter @exness/ws-server start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
